### ISSUE TITLE
upgrade

### ISSUE THREAD

**Issue by osaaso1** [excubo-ag/Blazor.Diagrams#55]
Hi
Please upgrade to Microsoft.Component......... 3.2

**Comment by stefanloerwald** [comment]
Hi @osaaso1,

could you please specify the exact packages that you see being outdated? To the best of my knowledge, every dependency is perfectly up to date.

Thanks
Stefan

**Comment by stefanloerwald** [comment]
As everything seems up-to-date, I'm closing this issue for now. Should there ever be something outdated, please do not hesitate to open an issue.
