### ISSUE TITLE
Fixed node demo not working

### ISSUE THREAD

**Issue by Epictek** [excubo-ag/Blazor.Diagrams#56]
I am still able to drag the "fixed node" on this demo https://excubo-ag.github.io/Blazor.Diagrams/fixed_node

**Comment by stefanloerwald** [comment]
Thanks for letting us know, @Epictek. A fix is on its way as part of commit cfb8c4d and version 2.1.15 which will become available momentarily: https://www.nuget.org/packages/Excubo.Blazor.Diagrams/2.1.15
