### ISSUE TITLE
Overview/Canvas does not respond to resize events

### ISSUE THREAD

**Issue by Epictek** [excubo-ag/Blazor.Diagrams#58]
To Replicate:
* Open https://excubo-ag.github.io/Blazor.Diagrams/with_overview
* Resize window and then refresh
* expand window and then look at overview, it will be the wrong size and dragging the diagram will cause nodes to disappear unexpectedly due to them being outside the canvas

![image](https://user-images.githubusercontent.com/1466270/97305318-d8e2e500-1854-11eb-97e2-33d72efd847b.png)

**Comment by stefanloerwald** [comment]
Thanks for bringing this issue to our attention. I'm working on a resolution which will be available in the next release

**Comment by stefanloerwald** [comment]
Fixed in version [3.0.1](https://www.nuget.org/packages/Excubo.Blazor.Diagrams/3.0.1), by commit 8d6d89f
