### ISSUE TITLE
Getting Diagrams to work, when installed as a Nuget package

### ISSUE THREAD

**Issue by rad765** [excubo-ag/Blazor.Diagrams#63]
Hello Steffan

i'm attemting to test your Diagram in a Server side Blazor app. It looks very promising, but I cant get it to work.

To reproduce:
I'm using Visual studio 2019 Preview.  
I created a new Blazor serverside test app.
I installed Excubo.Blazor.Diagrams from NuGet.
I  added: @using Excubo.Blazor.Diagrams to _Imports.Razor
I created a new Razor component for Diagram and inserted an exact copy of your componenet "WithLinkSelector.razor" (Have tried others to with same result) 

Run the app, and I get this result:
![image](https://user-images.githubusercontent.com/16493230/98347960-6a521400-2018-11eb-9e30-19daa9d27450.png)

(By the way, It works fine when I download the complete project, but I think it should work with NuGet to)

Ca you help me out?

**Comment by stefanloerwald** [comment]
Hi @rad765,

It seems like the component is correctly inserted, as we can see the link selector appearing in the top right. I suspect you're experiencing an issue with css. Maybe the nav menu is overlapping? If that's not the case, can you inspect the web site and see whether there are any errors logged to console? If you could paste the generated DOM, that could also help identify the issue.

BR
Stefan

**Comment by rad765** [comment]
Hi Stefan

Thank you for quick answer.

The CSS is the standard created by the project. Maybe I need to include something from the Diagram project? 
You don't mention that in the "How to Use"

In the DOM file I se there is a unhandles exeption. 
Debugging the code it crashes in the line
       private Arrow arrows { get; set; } = Arrow.Both;

I have attached a file with the DOM (I guess)
[DOM.txt](https://github.com/excubo-ag/Blazor.Diagrams/files/5500466/DOM.txt)


Thank you
René

**Comment by stefanloerwald** [comment]
From the DOM it looks like the height of the diagram is zero because of the parent element. The diagram component takes 100% of the height of the parent, so if that height is set to zero, that's how high the diagram will be.

**Comment by rad765** [comment]
Adding a "style="height:800px" in the MainLayout.Razor  made it. 
![image](https://user-images.githubusercontent.com/16493230/98354289-c5880480-2020-11eb-98e4-d1456bb90567.png)

I was using an out the box Blazor app, so maybe you should make note on this in the "How to Use"

Thank you very mutch
:-) René

**Comment by stefanloerwald** [comment]
Great that this solved it :-) Since this issue is very much dependent on what is around the diagram, and the used design framework (bootstrap, material, ...), I think it's best solved on a case-by-case basis. There's sadly no 100% correct way in handling this: it depends very much on how large you want the diagram to be and what is around the diagram.
