### ISSUE TITLE
Creating custom link

### ISSUE THREAD

**Issue by owenmorris** [excubo-ag/Blazor.Diagrams#73]
Firstly, thanks so much for putting this library out there - as some background I'm spiking out whether it is feasible that we can port an internal graphical application to Blazor from JS.  I've found it easy to use so far.

The application uses a kind of 'family tree' view and the built in AngledLink unfortunately does not break the line in the right place.  I was seeing if I could derive a custom link type and do the drawing myself.  

What I've tried (following the StraightLink and AngledLink examples) from the repo:
-  Inherited from LinkBase
- Drawing lines from ControlPoints.First() and ControlPoints.Last()

In my inherited component I am not seeing ControlPoints be populated and Source.X & Y aren't accessible because they're internal fields.  Is there an example available of how to do a custom link in a similar way to that available for the custom node example?

**Comment by stefanloerwald** [comment]
Hi @owenmorris,

thanks for your feedback. You're right that currently drawing custom links is not working. I'll add that to my backlog which I will start working on next week (as I'm still taking a few days off).

Thanks for your patience,
Stefan

**Comment by owenmorris** [comment]
Hi Stefan, I made the changes in the attached pull request  (#74)  locally, which allowed me to carry on.  Would appreciate any feedback when you get back from your break.

**Comment by stefanloerwald** [comment]
Hi @owenmorris,

thanks for submitting the PR. Is this really the only change necessary? I'm a bit surprised :-D

Stefan

**Comment by owenmorris** [comment]
Yes, I had to cargo-cult in the following snippet from one of the other components to get it to render, but that was all I needed for my fairly basic needs for this!

` 
if (ControlPointMethods == null)
        {
            ControlPointMethods = new List<Func<(double X, double Y)>>();
        }`

Could that go into LinkBase too?

**Comment by stefanloerwald** [comment]
That code couldn't be part of link base, as it is specific to the type of link. I'll think of the best way to make this work nicely. Let me just first merge the PR, so that you can continue working with the packaged version. More convenience to come soon...

**Comment by owenmorris** [comment]
Looks good, thanks again!
