### ISSUE TITLE
Property Hidden

### ISSUE THREAD

**Issue by MichaelLant** [excubo-ag/Blazor.Diagrams#77]
I am starting to create custom components and I have encountered something that I think is a bug.

My starting point was to 
- Create a new Blazor project and use the lastest NuGet package.
- Add a design surface and add a few nodes per the getting started guide.
- Create a new razor component as an empty shell and give it a name
- Copy the code from the Custom Node example into the new razor component
- Add in the appropriate usings

After doing all of this there is one property that does not resolve from the example file:

![image](https://user-images.githubusercontent.com/689502/106401908-d6180300-63f4-11eb-928c-3de2e815eafd.png)

I traced it back to Excubo.Blazor.Diagrams.NodBase where the property is defined as protected. As I am using a NuGet and not using the source in my application, I cannot access the property.

![image](https://user-images.githubusercontent.com/689502/106401821-38bccf00-63f4-11eb-8ab2-d288c0ae5354.png)

Am I misunderstanding something?

**Comment by stefanloerwald** [comment]
The property `Hidden` is a necessary construct for content-sized nodes (the nodes where the size of the content determines the size of the node, as opposed to fixed-size nodes, where the node itself can be sized by the user). It is only available if you inherit from `ContentSizedNodeBase`. The documentation should make it clearer that this wouldn't work with `FixedSizeNodeBase`.

For `FixedSizeNodeBase`-based node components, simply remove the entire line.

**Comment by mjlant** [comment]
Thank you for the clarification.
