### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by MichaelLant** [excubo-ag/Blazor.Diagrams#78]
I am trying to create some custom diagram shaped with specific properties. I am wondering 
1. if it is possible to accomplish with the Excubo library 
2. If it is possible, where would I start to do something like this and 
3. How much effort would it be.

I am not an experienced web developer, but I am in experienced C# developer and I have about six months of experience with Blazor, so I am feeling comfortable with the environment.

Here are the primary requirements.
- List container (Item) with an editable header.
- Arbitrary number of Subitems in the Items list
- Need to be able to add items to and remove them from the Subitems list. Ideally, this would be through databinding wherein items in the list show up or disappear visually in the UI as they are added to or removed from the list
- Containing Item objects must also be addable and removable
- Item Name and individual Subitem names are editable.
- Data binding to compound C# object that contains the parent object and a list of Items.
- Items and Subitems each have a dozen or so properties that, when an Item or SubItem is selected, i will show a Blazor comoponent that is a property instepctor/editor to the side fo the screen where the Item and Subitem properties will be editable.
- Need to enforce rules such as:
  - An outlet port (from a Subitem) can have only one connector line and it must be to an inlent port on an Item header
  - Item headers can have any number of incoming connections.
  - Item headers cannot have outlet ports
- Ports display as circles.
- Ports are hidden except if they either have a connection already made, or there is a mouse over event so that a connector line be originate from or be connected to the now visible port
- The Item container has a drop shadow. It took me a long time, but I have figured out how to do this, but I am sure that there is a better way to accomplish it.

Visually, this is what I am trying to accomplish - much like an ERD, but solving an entirely different problem, with different constraints and connection rules.

![image](https://user-images.githubusercontent.com/689502/106991962-65028380-6745-11eb-9c76-1c25eeedc4bd.png)

Looking forward to your feedback.

Michael

**Comment by stefanloerwald** [comment]
Hi Michael,

thanks for your message. This is quite a substantial list of requirements. Let me try to give my view on this:

Creating a custom node with a heading and list items underneath is possible for sure. The tricky thing will be to make it interactive in the right way:

- Editability: This is possible, but keep in mind that it's not trivial to distinguish between interactions with the node content and interactions with the node. E.g. when you want to be able to click the heading to edit it, but also move or select a node, you have a conflict of what a mouse click should do. I typically solve that by restricting the area that interacts with the node content to something smaller than the node.
- Node ports: Node ports are not a first-class part of this library. There's a feature for node-ports in all directions (top, top-right, right, ...), but that's not what you're looking for. The way this library handles connections, is by defining a border. The border doesn't have to have anything to do with the actual node shape, so the "border" can also be circles to the left and right of each item + heading. So far so good. The library itself won't stop you from breaking your requirements regarding connection count. This is something you'd need to handle yourself, i.e. delete a link when it's created in an invalid way.

That said, with such strict requirements, I think you'd actually be better off creating a fork and adding those requirements as direct features of the library.

Stefan

**Comment by MichaelLant** [comment]
Hi Stefan,

Thank you for the detailed response.

You have created an impressive body of work here. 

The work required for me to do to create components that suit my requirements seems a bit daunting at the moment due to the  amount of work necessary and more specifically, SVG manipulation, which until the last few days ago, Neither is my software development experience html/css based. All learnable, but one of the major reasons for using Blazor as opposed to using HTML/CSS/TypeScript, etc., the very things 

I will have to think this through before embarking on such an ambitious undertaking.

Thanks again for your help!

Michael
