### ISSUE TITLE
additional arrow styles?

### ISSUE THREAD

**Issue by returner** [excubo-ag/Blazor.Diagrams#81]
it's great library. thank you.

can you make additional arrow styles? like a dotted, dashed and so on.

please let me know as you possible.

**Comment by stefanloerwald** [comment]
Hi @returner,

did you try applying a CSS class or style to your link? E.g. `<StraightLink style="stroke-dasharray: 8 8;" ... />`.

Stefan

**Comment by returner** [comment]
ok, it works. thank you.
