### ISSUE TITLE
Is it possible to disable the function that lets you click on an object and link it to another?

### ISSUE THREAD

**Issue by CliveBennett** [excubo-ag/Blazor.Diagrams#82]
basically im trying to stop the user from accidently clicking the Diagram and drawing a line, in our use case adding new connectors shouldnt be possible, but I cant see how to disable that functionality?

![image](https://user-images.githubusercontent.com/29695733/116187737-2d223f80-a77a-11eb-8bae-529e138dce9f.png)

**Comment by stefanloerwald** [comment]
Hi @CliveBennett,

yes, this is possible! Just disable `AllowFreeFloatingLinks` on `Links`:

```html
<Diagram>
   <Nodes>
      ...
   </Nodes>
   <Links AllowFreeFloatingLinks="false">
      ...
   </Links>
</Diagram>
```

Hope that helps,
Stefan

**Comment by CliveBennett** [comment]
Thanks, yes I did try that option before, but it still lets me click and draw lines, 

  <Links AllowFreeFloatingLinks="false">
            @foreach (var lnk in FamilyDiagramNode.DiagramLinks)
            {
                <Link Source="lnk.Source" Target="lnk.Target" Arrow="Arrow.Target" Type="link_type" />

            }
        </Links>
        
        My whole Diagram is this
        
        <Diagram @ref="masterDiagram">
        <Nodes>
            @{double nodex = 0;}
            @{double nodey = 0;}


            @foreach (var node in FamilyDiagramNode.RectangleNodes)
            {
               
                <RectangleNode Id="@node.NodeId" >
                    @foreach (var q in node.Data)
                    {
                        <div>@((MarkupString)q)</div>
                    }
                </RectangleNode>

            }

        </Nodes>

        <Links AllowFreeFloatingLinks="false">
            @foreach (var lnk in FamilyDiagramNode.DiagramLinks)
            {
                <Link Source="lnk.Source" Target="lnk.Target" Arrow="Arrow.Target" Type="link_type" />

            }
        </Links>
        <NavigationSettings DisableZooming="false" />
        <AutoLayoutSettings Algorithm="SelectAutoScale.AutoScaleAlgorithm" @ref="autoLayout" />
        <OverviewSettings Position="Position.BottomRight" />

    </Diagram>

**Comment by stefanloerwald** [comment]
I'm surprised it wouldn't disallow free-floating links, because the code looks fine to me:

https://github.com/excubo-ag/Blazor.Diagrams/blob/e6a73622fd248330964b5e9375850901e8ff8029/Diagram/Diagram.MouseInteraction.razor.cs#L436

Could you please clarify which clicks are performed by the user and where your expectation of the behavior differs from the observed behavior?

**Comment by stefanloerwald** [comment]
Not sure whether I understood your question right in the first place. If you want to disable user-generated links entirely, see here: https://github.com/excubo-ag/Blazor.Diagrams/issues/79#issuecomment-774030730
