### ISSUE TITLE
Capture Drag Event of Node causes render to fail

### ISSUE THREAD

**Issue by antwjadam** [excubo-ag/Blazor.Diagrams#84]
I am trying to capture when a node is dragged on the diagram to update the datastore for the node with its new position on the diagram, thus persisting it between sessions.

Adding ondragend="DragEnd" to the node or nodes tag is causing the render to fail even though the handler is correctly defined. 

private void DragEnd(DragEventArgs e)
{
  // ... code will go here
}

I have also tried other standard blazor on... event handlers and they all seem to make the render fail when added to a node or link.

At the moment the nodes supports OnRemove and OnAdd, but not OnModified.

Please advise how I can catch when a node or group of nodes are moved on the diagram?

**Comment by stefanloerwald** [comment]
Hi @antwjadam,

Defining additional parameters (including event handlers) to nodes is generally not supported. You can get updates to the node positions by binding to their coordinates. That way, the property you're binding to is always kept up-to-date.

BR
Stefan

**Comment by antwjadam** [comment]
Yup, I have the binding to the co-ordinates, so that when retrieving my node list from the db, the diagram draws correctly. What I need though is to catch the event that the node on the diagram is dragged to a new position, The diagram rendered is showing the node in the new position fine, the x,y bindings give the new co-ordinates fine. But I need to trigger an update to the database to update the co-ordinates on the database record for that node.... something like in pseudo code

... node has moved event is triggered (this is the thing I cant work out - how to detect the change)
... get the new x,y from the bound values
... using the node id, find the node record on the database for that id (I can do this bit)
... update the x,y on the database to the new values (this is easy)

I did notice the selection change event triggers when clicking on the node to start dragging it, and fires again when releasing the node in its new position, so I though I could maybe using the reference to the diagram, step through all the nodes looking for x,y updates needed to be done on the db.

**Comment by stefanloerwald** [comment]
I see. While you can technically just modify the bind to perform more operations on ValueChanged, I would advise against that, because it would fire for every tiny little change, even during the move. I'm working on a larger code refactoring of mouse interaction at the moment, so I'll have a look into adding such an event while I'm at it.

**Comment by antwjadam** [comment]
Thanks!

At the moment, I am going to try this in my selection change event (its a bit sledge hammer to crack a nut but will get me what I need for now)

// all nodes deselected so check for x,y change
foreach (var nodeRendered in diagramNodes)
{
  var nodeDatabase = nodesService.GetNodeById(nodeRendered.Id);
  if (nodeRendered.X == nodeDatabase.X && nodeRendered.Y == nodeDatabase.Y) continue;
  nodesService.UpdateNodeXY(nodeRendered.Id, nodeRendered.X, nodeRendered.Y)
}

**Comment by stefanloerwald** [comment]
This is now part of v3.12.0: You get a `OnModified` event callback on the `Nodes`. Please let me know in case it doesn't work for you.
