### ISSUE TITLE
Is there a way to make lines not lap over nodes during auto layout

### ISSUE THREAD

**Issue by ZeroRadius** [excubo-ag/Blazor.Diagrams#85]
Hello, this isn't an issue with the project itself but I did not know where else to ask it. We are looking at the auto arrange feature  and the lines keep intersecting the other nodes. IS there anything in this library that allows you to avoid intersecting nodes and is there a way to get text on the line (i believe the lines were of type nodeLink)

**Comment by stefanloerwald** [comment]
Hi @ZeroRadius,

both of the features you mention would be absolutely wonderful, but so far we haven't yet implemented them. As we don't have those needs internally, we can't promise adding these any time soon. Of course we welcome contributions via pull requests.

Sorry to not have better news for you.
Best regards
Stefan

**Comment by ZeroRadius** [comment]
Hi, thank you so much for the response and for all your work on this wonderful library. Unfortunately I was wanting to use it for work and have a very tight deadline so I won't be able to help on it at this time.
