### ISSUE TITLE
Panning on mobile

### ISSUE THREAD

**Issue by CliveBennett** [excubo-ag/Blazor.Diagrams#87]
Hi, is panning on mobile supported?.  My diagram renders fine on an iPhone, but when its off screen I cant touch the screen and drag the diagram around. 
Appears to be the same with the Demo site as well.

Cheers

**Comment by stefanloerwald** [comment]
Hi @CliveBennett,

I'm sorry to say that touch interaction is not supported and there's no timeline for its support either. If you need it, your best course of action is a PR ;-)

Best regards
Stefan

**Comment by CliveBennett** [comment]
> Hi @CliveBennett,
> 
> I'm sorry to say that touch interaction is not supported and there's no timeline for its support either. If you need it, your best course of action is a PR ;-)
> 
> Best regards
> Stefan

No worries, ill see if I get time to have a play with it.
