### ISSUE TITLE
Allow custom middle point and link direction of AngleLink component

### ISSUE THREAD

**Issue by nguyenvanbien95** [excubo-ag/Blazor.Diagrams#88]
Hi, I am use your library for my project. Thank for your work. 
But I can custom AngleLink component. 
So you can allow custom middle point and link direction of AngleLink component?

**Comment by stefanloerwald** [comment]
Hi @nguyenvanbien95,

when you click on an angled link, it becomes editable. You can then click&drag the middle control point and move it around as you please.

Does that solve your issue?

BR
Stefan

**Comment by nguyenvanbien95** [comment]
Hi @stefanloerwald, 
It is require user action. In my case, all nodes and links are auto generated. So I can not control link render.

**Comment by stefanloerwald** [comment]
In that case, unfortunately, this cannot be done, as the control points of links cannot be modified programatically.

**Comment by nguyenvanbien95** [comment]
I saw source code and find something. Middle point and direction of link can be modified by pass as Parameter.

**Comment by stefanloerwald** [comment]
As I've said, the control points are not exposed publically, so there's no supported way of modifying them. See https://github.com/excubo-ag/Blazor.Diagrams/blob/main/Diagram/LinkBase.cs#L127

You are of course free to use reflection to change values, as always in C#.

**Comment by nguyenvanbien95** [comment]
Oke, thanks for your support!
