### ISSUE TITLE
Adding container element/nesting of nodes

### ISSUE THREAD

**Issue by DTjassens** [excubo-ag/Blazor.Diagrams#90]
Have you thought about adding support for nesting nodes? So I guess that means defining a container node type. I hope i didn't overlook an already existing functionality for this :-)

**Comment by stefanloerwald** [comment]
Nesting nodes is not intended, but I guess it also kind of depends on what you mean by that: how would nested nodes behave? Can a nested node be unnested or is it entirely and permanently constraint to the node? Can links be formed between nodes outside?

It seems like a rather complex requirement to me, so not sure how well suited this library is for you.
