### ISSUE TITLE
Auto-Center after ZoomToFit

### ISSUE THREAD

**Issue by Phloog** [excubo-ag/Blazor.Diagrams#93]
Hi,

is there a way to make the diagram auto-center (in other words: pan/translate automatically so that the diagram's nodes are centered in the viewport) after calling ZoomToFit? Can I implement this by myself ("from the outside") or is it neccessary to add code to the Blazor.Diagrams lib?

Thanks,
Tim

**Comment by stefanloerwald** [comment]
Hi Tim,

I'm not sure I understand the expected outcome here. Could you please provide screenshots of the result after ZoomToFit and of your expected layout?

Thanks
Stefan

**Comment by Phloog** [comment]
Hi, sure!

The first screenshot is after zoom&fit, and the second is how I'd like it to be translated (the card encompasses the canvas fully).

![2023-06-06 08_09_15-SB Central](https://github.com/excubo-ag/Blazor.Diagrams/assets/2299409/695b2374-8679-4b3b-9b15-b7d7a5ea982d)

![2023-06-06 08_09_33-SB Central](https://github.com/excubo-ag/Blazor.Diagrams/assets/2299409/6972b2dd-8fb9-4bf1-968e-57b5b2653f6c)

So it'd need to determine the bounding box size of the zoomed full diagram, and the current size of the viewport, and then pan accordingly

**Comment by stefanloerwald** [comment]
I see! Thanks for clarifying this.

I don't think it will be possible to achieve this without modification of the library code, but that shouldn't be too difficult. Zoom to fit already does most of what you need, but the anchor for this operation is the top left corner, whereas you want it in the center of the screen.

If I remember the code correctly, it measures the most extreme points of all nodes and then adjusts pan and zoom to fit those, for which it needs the diagram size as well. Changing the anchor would mean adjusting the pan slightly, which isn't a big deal (essentially add a horizontal and vertical offset of half the difference between width/height and maximum difference between left-most&right-most/top-most&bottom-most points).

I'd be very happy to review a pull request for this. It could be a new method "ZoomToFitCenter" or maybe a parameter to the existing method (default should keep existing behaviour).

Would you be willing to implement this?

Thanks
Stefan

**Comment by Phloog** [comment]
Sure, as soon as I find time I'll look into this!

**Comment by Phloog** [comment]
Hi Stefan,

after updating to 4.1.0, the method ZoomToFitCentered is still not available on Diagram.

**Comment by stefanloerwald** [comment]
Hi @Phloog, can you please try again with v4.1.5? Thanks.

**Comment by Phloog** [comment]
After updating to 4.1.5, the method is available, thank you! :-)
